apiVersion: apps/v1
kind: Deployment
metadata:
  name: osd-example-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: osd-example-operator
  template:
    metadata:
      labels:
        name: osd-example-operator
    spec:
      serviceAccountName: osd-example-operator
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      containers:
        - name: osd-example-operator
          image: quay.io/redhat-services-prod/oeo-cicada-tenant/osd-example-operator@sha256:3060ce2df4ceb8d35080bfb9d63f08a88ba53725d77c646a775baf2689ce7667
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
